### ISSUE TITLE
/tmp/sources.sh 没有赋予执行权限

### ISSUE THREAD

**Issue by FishGoddess** [yasarluo/webman-dock#1]
在 COPY 完 sources.sh 文件之后，没有执行 chmod +x 命令赋予执行权限，在构建镜像时会报错。。。
详情看这行：https://github.com/yasarluo/webman-dock/blob/79981d85dbfd36fc391bea5566c5a3bc165373fa/Dockerfile#L12

**Comment by yasarluo** [comment]
fixed, tks
